### ISSUE TITLE
Signed Nuget package from wrong party?

### ISSUE THREAD

**Issue by thomas3d** [viniciuschiele/Scrypt#5]
Hi. 
First of all, thanks for a good project. 

Look at the attached screen dump from Nuget package manager in Visual Studio. 
The signed version is by RabbitSoftware not by Vinicius Chiele as I would expect. 
Also the version is older. 
Should I not use the Signed version?

![scrype net](https://cloud.githubusercontent.com/assets/3169220/20273821/03cadfc2-aa93-11e6-9989-dbc99e7f1ebc.png)

**Comment by viniciuschiele** [comment]
Hi @thomas3d 

I don't provide nor use this signed version, I believe that library is a fork from my library created by another person/company.
So if you don't need a signed version better to use my library.

Cheers!

**Comment by thomas3d** [comment]
Thanks for your quick answer. We will use your version. 
Thanks again for providing this software open source. 
//Thomas3D
