### ISSUE TITLE
Add salt?

### ISSUE THREAD

**Issue by ArashMotamedi** [viniciuschiele/Scrypt#8]
Hello. This is a question, not an issue. 

In the article you've referenced from CrackStation, the suggestion is to generate a salt, prepend it to the password, and then hash the concatenated string. Looking at your API, I initially thought that I perhaps needed to do that salting part manually, and then pass the salted password to the Encode method. But then I looked at the source code and noticed that you seem to take care of the salting step already.

So, do I understand this correctly that the Encode method salts the password and the the salt is embedded somewhere in the output of this method? Does this mean that I don't need to pre-salt the password before passing it into Encode, and also I don't need to store that salt separately in my database? 

Thanks,
Arash

**Comment by viniciuschiele** [comment]
Hi,

Exactly, the ```Encode``` method will generate a salt using by default ```RNGCryptoServiceProvider``` which is a good random number generator, the output will be a string containing the settings + salt + hashed password, pretty much similar to BCrypt.

So yes, you don't need to pre-salt nor store the salt separately.

Cheers
