### ISSUE TITLE
Maximum iteration count

### ISSUE THREAD

**Issue by sandord** [viniciuschiele/Scrypt#9]
When the `ExtractHeader` extracts the iteration count, it does not support iteration counts higher than 65535. Is this by design? In that case, at least the constructor should throw when specifying an iteration count that is too high.

    iterationCount = (int)config >> 16 & 0xffff;

**Comment by sandord** [comment]
By the way, this effectively makes the maximum iteration count 32768 because it has to be a power of 2.

**Comment by viniciuschiele** [comment]
You are right, I should use an integer to hold the iterationCount, the max value would be 2,147,483,647 which looks enough.
I guess most people (including me) are just using the default value, I will get that fixed and add some unit tests for that.
Thanks

**Comment by viniciuschiele** [comment]
I just released a new version that fixes this issue.
Thanks

**Comment by sandord** [comment]
:+1:
